swagger: "2.0"
info:
  title: Auth API
  version: 1.0.0
paths:
  /auth/register:
    post:
      summary: Register user
      description: Use this endpoint to register a new user.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: user
          in: body
          description: User data
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
            example:
              name: Test User
              email: test@user.com
              password: pass@123
      responses:
        200:
          description: Successful registration
          schema:
            type: object
            properties:
              message:
                type: string
  /auth/login:
    post:
      summary: Authenticate user
      description: Use this endpoint to authenticate a user and generate a token.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: credentials
          in: body
          description: User credentials
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
            example:
              email: test@user.com
              password: pass@123
      responses:
        200:
          description: Successful authentication
          schema:
            type: object
            properties:
              token:
                type: string