definitions:
  CreateProject:
    type: object
    properties:
      id:
        type: integer
        format: int64
      workPackageId:
        type: string
      name:
        type: string
      description:
        type: string
      startDate:
        type: string
        format: date-time
      endDate:
        type: string
        format: date-time
      status:
        type: string
        enum:
          - ACTIVE
          - INACTIVE
      deliveryManagerId:
        type: integer
        format: int64
      projectManagerId:
        type: integer
        format: int64
    required:
      - id
      - workPackageId
      - name
      - startDate
      - endDate
      - status
      - deliveryManagerId
      - projectManagerId
    example:
      id: 1
      workPackageId: "WP-1"
      name: "Project 1"
      description: "Project 1 description"
      startDate: "2020-01-01T00:00:00Z"
      endDate: "2020-12-31T23:59:59Z"
      status: "ACTIVE"
      deliveryManagerId: 1
      projectManagerId: 2
paths:
  /projects:
    post:
      summary: Create a project
      operationId: createProject
      tags:
        - project
      parameters:
        - in: body
          name: project
          description: The project to create
          required: true
          schema:
            $ref: '#/definitions/CreateProject'
      responses:
        '201':
          description: Created
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error